/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin-section': RouteRecordInfo<'/admin-section', '/admin-section', Record<never, never>, Record<never, never>>,
    '/forgotten-password': RouteRecordInfo<'/forgotten-password', '/forgotten-password', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/match-detail': RouteRecordInfo<'/match-detail', '/match-detail', Record<never, never>, Record<never, never>>,
    '/match-list': RouteRecordInfo<'/match-list', '/match-list', Record<never, never>, Record<never, never>>,
    '/new-admin': RouteRecordInfo<'/new-admin', '/new-admin', Record<never, never>, Record<never, never>>,
    '/new-match': RouteRecordInfo<'/new-match', '/new-match', Record<never, never>, Record<never, never>>,
    '/new-match-confirm': RouteRecordInfo<'/new-match-confirm', '/new-match-confirm', Record<never, never>, Record<never, never>>,
    '/new-team': RouteRecordInfo<'/new-team', '/new-team', Record<never, never>, Record<never, never>>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/seasons-administration': RouteRecordInfo<'/seasons-administration', '/seasons-administration', Record<never, never>, Record<never, never>>,
    '/team-administration': RouteRecordInfo<'/team-administration', '/team-administration', Record<never, never>, Record<never, never>>,
    '/team-list': RouteRecordInfo<'/team-list', '/team-list', Record<never, never>, Record<never, never>>,
  }
}
